
# Input list with parties for diputados without website info --------------


# Input information for the non-present
party_input <- tribble(
  ~diputado_id, ~party,
  132, "Renovación Nacional",
  137, "Partido Demócrata Cristiano",
  150, "Partido Socialista",
  155, "Renovación Nacional",
  169, "Partido Por la Democracia",
  175, "Unión Demócrata Independiente",
  176, "Partido Socialista",
  178, "Renovación Nacional",
  179, "Unión Demócrata Independiente",
  206, "Independientes",
  208, "Unión Demócrata Independiente",
  211, "Partido Por la Democracia",
  220, "Partido Demócrata Cristiano",
  222, "Partido Demócrata Cristiano",
  239, "Partido Demócrata Cristiano",
  802, "Partido Socialista",
  806, "Renovación Nacional",
  821, "Unión Demócrata Independiente",
  822, "Unión Demócrata Independiente",
  858, "Partido Demócrata Cristiano",
  864, "Unión Demócrata Independiente",
  870, "Partido Socialista",
  873, "Partido Por la Democracia",
  877, "Partido Demócrata Cristiano",
  887, "Unión Demócrata Independiente",
  906, "Unión Demócrata Independiente",
  932, "Partido Demócrata Cristiano",
  933, "Partido Demócrata Cristiano",
  962, "Unión Demócrata Independiente",
  158, "Partido Por la Democracia",
  177, "Partido Por la Democracia",
  181, "Partido Demócrata Cristiano",
  193, "Partido Socialista",
  195, "Partido Socialista",
  205, "Partido Por la Democracia",
  224, "Partido Demócrata Cristiano",
  804, "Partido Socialista",
  805, "Unión Demócrata Independiente",
  818, "Renovación Nacional",
  819, "Partido Por la Democracia",
  832, "Partido Socialista",
  834, "Renovación Nacional",
  841, "Partido Demócrata Cristiano",
  860, "Partido Demócrata Cristiano",
  863, "Renovación Nacional",
  871, "Unión Demócrata Independiente",
  884, "Unión Demócrata Independiente",
  892, "Partido Por la Democracia",
  904, "Partido Por la Democracia",
  912, "Renovación Nacional",
  914, "Partido Radical de Chile",
  140, "Partido Demócrata Cristiano",
  159, "Unión Demócrata Independiente",
  161, "Renovación Nacional",
  165, "Unión Demócrata Independiente",
  170, "Partido Demócrata Cristiano",
  187, "Unión Demócrata Independiente",
  190, "Partido Demócrata Cristiano",
  213, "Partido Demócrata Cristiano",
  221, "Partido Por la Democracia",
  807, "Unión Demócrata Independiente",
  814, "Renovación Nacional",
  817, "Partido Socialista",
  825, "Renovación Nacional",
  826, "Unión Demócrata Independiente",
  828, "Unión Demócrata Independiente",
  842, "Renovación Nacional",
  849, "Partido Por la Democracia",
  854, "Partido Por la Democracia",
  859, "Partido Por la Democracia",
  878, "Partido Demócrata Cristiano",
  881, "Renovación Nacional",
  889, "Unión Demócrata Independiente",
  899, "Partido Por la Democracia",
  918, "Partido Demócrata Cristiano",
  921, "Renovación Nacional",
  947, "Partido Demócrata Cristiano",
  151, "Unión Demócrata Independiente",
  164, "Independientes",
  166, "Independientes",
  173, "Partido Radical de Chile",
  185, "Partido Demócrata Cristiano",
  202, "Partido Demócrata Cristiano",
  209, "Independientes",
  226, "Partido Demócrata Cristiano",
  234, "Unión Demócrata Independiente",
  242, "Renovación Nacional",
  800, "Partido Por la Democracia",
  808, "Partido Demócrata Cristiano",
  812, "Unión Demócrata Independiente",
  813, "Renovación Nacional",
  816, "Partido Demócrata Cristiano",
  823, "Unión Demócrata Independiente",
  830, "Unión Demócrata Independiente",
  840, "Unión Demócrata Independiente",
  857, "Unión Demócrata Independiente",
  868, "Renovación Nacional",
  882, "Independientes",
  886, "Partido Por la Democracia",
  888, "Partido Radical de Chile",
  890, "Independientes",
  894, "Partido Demócrata Cristiano",
  895, "Unión Demócrata Independiente",
  902, "Partido Por la Democracia",
  903, "Independientes",
  907, "Unión Demócrata Independiente",
  910, "Partido Por la Democracia",
  916, "Partido Por la Democracia",
  801, "Renovación Nacional",
  809, "Unión Demócrata Independiente",
  820, "Renovación Nacional",
  824, "Partido Socialista",
  829, "Partido Demócrata Cristiano",
  831, "Unión Demócrata Independiente",
  833, "Partido Socialista",
  835, "Independientes",
  836, "Partido Radical de Chile",
  838, "Unión Demócrata Independiente",
  839, "Partido Por la Democracia",
  845, "Partido Por la Democracia",
  846, "Renovación Nacional",
  847, "Partido Demócrata Cristiano",
  851, "Renovación Nacional",
  852, "Partido Por la Democracia",
  853, "Independientes",
  861, "Unión Demócrata Independiente",
  867, "Renovación Nacional",
  874, "Unión Demócrata Independiente",
  876, "Partido Por la Democracia",
  880, "Partido Socialista",
  883, "Partido Socialista",
  891, "Renovación Nacional",
  896, "Renovación Nacional",
  900, "Partido Radical de Chile",
  901, "Partido Socialista",
  905, "Unión Demócrata Independiente",
  909, "Renovación Nacional",
  911, "Partido Demócrata Cristiano",
  915, "Renovación Nacional",
  919, "Unión Demócrata Independiente",
  922, "Partido Por la Democracia",
  924, "Partido Socialista",
  927, "Renovación Nacional",
  928, "Unión Demócrata Independiente",
  929, "Partido Por la Democracia",
  930, "Partido Comunista",
  934, "Partido Demócrata Cristiano",
  935, "Renovación Nacional",
  938, "Unión Demócrata Independiente",
  939, "Unión Demócrata Independiente",
  941, "Partido Socialista",
  943, "Independientes",
  944, "Unión Demócrata Independiente",
  948, "Renovación Nacional",
  951, "Unión Demócrata Independiente",
  954, "Unión Demócrata Independiente",
  955, "Unión Demócrata Independiente",
  958, "Partido Por la Democracia",
  960, "Partido Por la Democracia",
  964, "Unión Demócrata Independiente",
  965, "Unión Demócrata Independiente",
  966, "Unión Demócrata Independiente",
  969, "Partido Demócrata Cristiano",
  970, "Unión Demócrata Independiente",
  977, "Partido Demócrata Cristiano",
  978, "Unión Demócrata Independiente",
  979, "Independientes",
  980, "Partido Por la Democracia",
  983, "Partido Demócrata Cristiano",
  988, "Evolución Política",
  1004, "Partido Socialista",
  1007, "Partido Por la Democracia",
  1026, "Renovación Nacional",
  844, "Unión Demócrata Independiente",
  949, "Renovación Nacional",
  990, "Partido Socialista",
  992, "Partido Demócrata Cristiano",
  996, "Partido Demócrata Cristiano",
  997, "Independientes",
  998, "Partido Demócrata Cristiano")


# Input for political changes ---------------------------------------------
















